# Generated by Django 5.2.7 on 2025-10-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('education', models.CharField(choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=50, verbose_name='学历')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业院校')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('base', models.CharField(default='远程', max_length=50, verbose_name='所在地区')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='工作经历')),
                ('cooperation_status', models.CharField(choices=[('合作', '合作'), ('合作较差', '合作较差')], default='合作', max_length=20, verbose_name='合作状态')),
                ('match_level', models.CharField(choices=[('A', 'A - 有经验，较匹配'), ('B', 'B - 无经验，项目经验丰富'), ('C', 'C - 有经验，匹配度一般'), ('D', 'D - 无经验，匹配度一般'), ('E', 'E - 匹配度低')], default='D', max_length=5, verbose_name='简历匹配度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人库',
            },
        ),
        migrations.CreateModel(
            name='CooperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称/岗位')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色/岗位')),
                ('evaluation', models.TextField(blank=True, null=True, verbose_name='表现评价')),
                ('cooperation_result', models.CharField(choices=[('优秀', '优秀'), ('良好', '良好'), ('一般', '一般'), ('不再合作', '不再合作')], max_length=50, verbose_name='合作结果')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperations', to='candidates.candidate', verbose_name='候选人')),
            ],
            options={
                'verbose_name': '合作记录',
                'verbose_name_plural': '合作记录',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('labor_contract', '劳动合同'), ('intern_agreement', '实习/兼职协议'), ('nda', '保密协议'), ('resume', '简历'), ('other', '其他')], max_length=50, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='documents/', verbose_name='文件')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate', verbose_name='候选人')),
            ],
            options={
                'verbose_name': '档案文件',
                'verbose_name_plural': '档案文件',
            },
        ),
    ]
