# Generated by Django 5.2.7 on 2025-10-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='简历文件'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cooperation_status',
            field=models.CharField(choices=[('未合作', '未合作'), ('合作', '合作'), ('合作较差', '合作较差')], default='未合作', max_length=20, verbose_name='合作状态'),
        ),
    ]
