# Generated by Django 5.2.7 on 2025-10-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_candidate_resume_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cooperationrecord",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "合作记录",
                "verbose_name_plural": "合作记录",
            },
        ),
        migrations.AddField(
            model_name="cooperationrecord",
            name="agreement_file",
            field=models.FileField(
                blank=True, null=True, upload_to="agreements/", verbose_name="兼职协议"
            ),
        ),
        migrations.AddField(
            model_name="cooperationrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="cooperationrecord",
            name="salary",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="薪资"
            ),
        ),
        migrations.AlterField(
            model_name="cooperationrecord",
            name="cooperation_result",
            field=models.CharField(
                choices=[("优秀", "优秀"), ("良好", "良好"), ("一般", "一般"), ("不再合作", "不再合作")],
                default="良好",
                max_length=50,
                verbose_name="合作结果",
            ),
        ),
        migrations.AlterField(
            model_name="cooperationrecord",
            name="evaluation",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="表现评价"
            ),
        ),
    ]
